
name: COVID Kaggle Gráficos

on:
  workflow_dispatch:

jobs:
  gerar-graficos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas matplotlib
      - name: Gerar gráficos com dados do Kaggle
        run: python script_kaggle.py
